// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/posts/modules/posts/controller"
	"github.com/atom-apps/posts/modules/posts/dto"
	"github.com/atom-apps/posts/common"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeBookController(engine fiber.Router, controller *controller.BookController) {
	groupPrefix := "/"+strings.TrimLeft(engine.(*fiber.Group).Prefix,"/")
	engine.Get(strings.TrimPrefix("/v1/posts/books/:id<int>", groupPrefix), DataFunc1(controller.Show, Integer[uint64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/v1/posts/books", groupPrefix), DataFunc3(controller.List, Query[dto.BookListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Post(strings.TrimPrefix("/v1/posts/books", groupPrefix), Func1(controller.Create, Body[dto.BookForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/v1/posts/books/:id<int>", groupPrefix), Func2(controller.Update, Integer[uint64]("id", PathParamError), Body[dto.BookForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/v1/posts/books/:id<int>", groupPrefix), Func1(controller.Delete, Integer[uint64]("id", PathParamError)))
}
