// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/posts/modules/posts/controller"
	"github.com/atom-apps/posts/modules/posts/dto"
	"github.com/atom-apps/posts/common"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeArticleDigController(engine fiber.Router, controller *controller.ArticleDigController) {
	groupPrefix := "/"+strings.TrimLeft(engine.(*fiber.Group).Prefix,"/")
	engine.Get(strings.TrimPrefix("/v1/posts/articles/:articleId<int>/dig/:id<int>", groupPrefix), DataFunc2(controller.Show, Integer[int]("articleId", PathParamError), Integer[uint64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/v1/posts/articles/:articleId<int>/dig", groupPrefix), DataFunc4(controller.List, Integer[int]("articleId", PathParamError), Query[dto.ArticleDigListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Post(strings.TrimPrefix("/v1/posts/articles/:articleId<int>/dig", groupPrefix), Func2(controller.Create, Integer[int]("articleId", PathParamError), Body[dto.ArticleDigForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/v1/posts/articles/:articleId<int>/dig/:id<int>", groupPrefix), Func3(controller.Update, Integer[int]("articleId", PathParamError), Integer[uint64]("id", PathParamError), Body[dto.ArticleDigForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/v1/posts/articles/:articleId<int>/dig/:id<int>", groupPrefix), Func2(controller.Delete, Integer[int]("articleId", PathParamError), Integer[uint64]("id", PathParamError)))
}
