// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/posts/modules/posts/controller"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeArticleContentController(engine fiber.Router, controller *controller.ArticleContentController) {
	groupPrefix := "/"+strings.TrimLeft(engine.(*fiber.Group).Prefix,"/")
	engine.Get(strings.TrimPrefix("/v1/posts/articles/:articleId<int>/contents/:id<int>", groupPrefix), DataFunc2(controller.Show, Integer[int]("articleId", PathParamError), Integer[uint64]("id", PathParamError)))
}
