// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm/schema"
)

const TableNameArticleTag = "article_tags"

// ArticleTag mapped from table <article_tags>
type ArticleTag struct {
	ID        uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	CreatedAt time.Time `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                 // 创建时间
	ArticleID uint64    `gorm:"column:article_id;type:bigint unsigned;comment:文章ID" json:"article_id"`             // 文章ID
	TagID     uint64    `gorm:"column:tag_id;type:bigint unsigned;comment:标签ID" json:"tag_id"`                     // 标签ID
}

func (*ArticleTag) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameArticleTag
	}
	return namer.TableName(TableNameArticleTag)
}
