// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

const TableNameChapter = "chapters"

// Chapter mapped from table <chapters>
type Chapter struct {
	ID          uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"`      // ID
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                      // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3);comment:更新时间" json:"updated_at"`                      // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:删除时间" json:"deleted_at" swaggertype:"string"` // 删除时间
	TenantID    uint64         `gorm:"column:tenant_id;type:bigint unsigned;comment:租户ID" json:"tenant_id"`                    // 租户ID
	UserID      uint64         `gorm:"column:user_id;type:bigint unsigned;comment:用户ID" json:"user_id"`                        // 用户ID
	BookID      uint64         `gorm:"column:book_id;type:bigint unsigned;comment:书ID" json:"book_id"`                         // 书ID
	Title       string         `gorm:"column:title;type:varchar(128);not null;comment:章节名" json:"title"`                       // 章节名
	Description string         `gorm:"column:description;type:varchar(256);not null;comment:简介" json:"description"`            // 简介
	Content     string         `gorm:"column:content;type:text;comment:详细介绍" json:"content"`                                   // 详细介绍
}

func (*Chapter) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameChapter
	}
	return namer.TableName(TableNameChapter)
}
